version: '3.8'

services:

  server:
    build:
      context: ../../
      dockerfile: docker/dev/server/Dockerfile
    networks:
      - local
    container_name: server
    expose:
      - "8080"
    ports:
      - 8080:8080

networks:
  local:
